config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /pt-BR|en/ do
    devise_for :users, controllers: { registrations: 'resgistration_users/registrations' }
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :reservations
    
    resources :users
    
    root 'reservations#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user

  enum reservation_type: { laboratorio: 1, infocentro: 2 }

  validates :reservation_date, presence: true
  validates :reservation_type, presence: true

  def number_laboratorio
    self.class.laboratorio.count
  end

  def number_infocentro
    self.class.infocentro.count
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations

  enum user_type: { chefe_de_turma: 0, professor: 1 }

  validates :name, presence: true
  validates :cpf, presence: true, length: { is: 11 }
  validates :phone, presence: true
  validates :registration_number, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, :trackable, :timeoutable, :registerable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  around_action :switch_locale

  private
  
  def default_url_options
    { locale: I18n.locale }
  end


  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  def user_not_authorized
    flash[:alert] = "Você não tem autorização para acessar essa página!"
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[edit update show destroy]

  def index
    @reservations = policy_scope(Reservation.order(:reservation_date))
  end

  def show; end

  def new
    @reservation = Reservation.new
    authorize @reservation
  end

  def create 
    @reservation = Reservation.new(reservation_params)
    authorize @reservation
    
    if @reservation.save
      flash[:success] = 'Reserva cadastrada com sucesso!'
      redirect_to reservations_path
    else 
      render 'new'
    end
  end

  def edit; end

  def update
    if @reservation.update(reservation_params)
      flash[:success] = 'Reserva atualizada com sucesso!'
      redirect_to reservations_path
    else
      render 'edit'
    end
  end

  def destroy
    @reservation.destroy
    flash[:success] = 'Reserva excluída com sucesso!'
    redirect_to reservations_path
  end

  private 
    def reservation_params
      params.require(:reservation).permit(:reservation_date, :reservation_type, :user_id)
    end

    def set_reservation
      @reservation = policy_scope(Reservation).find(params[:id])
      authorize @reservation
    end
end

app/controllers/resgistration_users/registrations_controller.rb
# frozen_string_literal: true

class ResgistrationUsers::RegistrationsController < Devise::RegistrationsController
  skip_before_action :require_no_authentication, only: [:new, :create]
  before_action :sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    build_resource
    yield resource if block_given?

    authorize resource
  end

  # POST /resource
  def create
    build_resource(sign_up_params)

    authorize resource

    if resource.save
      flash[:sucess] = 'Usuário cadastrado com sucesso!'

      redirect_to root_path
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name,
                                    :cpf, :phone, :registration_number, :user_type)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for
    root_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<%
=begin%>
 <% if object.errors.any? %>
  <div class="">
    <div class="alert alert-danger">
      Ops! Encontramos <%= pluralize(object.errors.count, 'erro', 'errors') %>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div> 
<% end %> 
<%
=end%>

app/views/layouts/_topnavbar.html.erb
<% if user_signed_in? %>
  <div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      <%= current_user.name %>
    </button>
    <ul class="dropdown-menu">
      <li>
        <%= link_to t('devise.registrations.edit.title', resource: current_user.class.model_name.human), edit_user_registration_path, class: 'dropdown-item' %>
      </li>
      <li><hr class="dropdown-divider"></li>
      <li>
        <%= link_to t('devise.sessions.logout'), destroy_user_session_path,  method: :delete, class: 'dropdown-item' %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LaboratoryReservation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap icons -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <!-- -->
    <!-- Bootstrap -->
    <%= javascript_include_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js' %>
    <!-- -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'layouts/topnavbar' %>
    <div>
      <% flash.each do |message_type, message| %>
        <%= content_tag 'div', class: "alert alert-#{message_type} alert-dismissible", role: 'alert' do %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span arua-hidden="true">&times;</span>
          </button>
          <%= message %>
        <% end %>
      <% end %>

      <%= yield %>

    </div> 
  </body>
</html>

app/views/reservations/_form.html.erb
<div class="row">
  <div class="form-group" id="reservation-date">
    <%= f.label :reservation_date, t('activerecord.attributes.reservation.reservation_date') %>
    <%= f.date_field :reservation_date, class: 'form-control', id: 'date' %>
  </div>

  <div id="select">
    <%= f.select :reservation_type, options_for_select(Reservation.reservation_types.keys.map { |type| [type.humanize, type] }) %>
  </div>

  <div id="select">
    <%= f.collection_select(:user_id, User.all, :id, :name, prompt: "Selecione o reservante") %>
  </div>
</div>

app/views/reservations/edit.html.erb
<h1>Editar Reserva</h1>
<div class="row" id="new">
  <div>
    <%= form_for @reservation do |f| %>
    
    <%= render 'form', f: f %>

    <div>
      <%= f.submit 'Atualizar', class: 'btn btn-success' %>
    </div>

    <% end %>

    <div class="back-button">
      <%= link_to 'Voltar', root_path, class: 'btn btn-success'%>
    </div>
    
  </div>
</div>

app/views/reservations/index.html.erb
<h1>Reserva de Laboratório</h1>
<table class="table table-bordered border-primary">
  <thead>
    <tr>
      <th scope="col" id="n-reservation">Nº de Reservas</th>
      <th scope="col">Data</th>
      <th scope="col">Tipo</th>
      <th scope="col">Reservante</th>
      <% if policy(:user).edit? || policy(:user).destroy? %>
        <th scope="col" class="table-actions-col">Ações</th> 
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each_with_index do |reservation, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>

        <td><%= reservation.reservation_date %></td>

        <td><%= reservation.reservation_type %></td>
      
        <td><%= reservation.user.name%></td>

        <% if policy(:reservation).edit? %>
          <td class="table-actions-col">
            <%= link_to edit_reservation_path(reservation), class: 'text-decoration-none' do %>
              <i class="bi bi-pencil-square"></i>
            <% end %>
        <% end %>  
        <% if policy(:reservation).destroy? %>  
            <%= link_to reservation_path(reservation), method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' } do %>
              <i class="bi bi-trash-fill"></i>         
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>  
  </tbody>
</table>
<% if policy(:user).create? %>
  <div id="button-reservation">
    <button class="register-button"><%= link_to 'Cadastrar nova Reserva', new_reservation_path, class: 'register-link' %></button>
    <button class="register-button"><%= link_to 'Cadastrar Reservante', new_user_registration_path, class: 'register-link' %></button>
  </div>
<% end %>

app/views/reservations/new.html.erb
<h1>Cadastrar Reserva</h1>
<div class="row" id="new">
  <div>
    <%= form_for @reservation do |f| %>
    
    <%= render 'form', f: f %>

    <div>
      <%= f.submit 'Cadastrar', class: 'btn btn-success' %>
    </div>

    <% end %>

    <div class="back-button">
      <%= link_to 'Voltar', root_path, class: 'btn btn-success'%>
    </div>

  </div>

</div>